---

python_enabled: yes                 # The role is enabled
python_ppa: ppa:fkrull/deadsnakes   # Python PPA
python_versions: [2.7, 3.4]         # Set versions (2.6, 2.7, 3.3, 3.4) which will be installed

python_install: []                  # Set packages to install globally
python_virtualenvs: []              # Create virtualenvs
                                    # Ex: python_virtualenvs:
                                    #     - path: /path/to/venv
                                    #     - path: /path/to/another/venv
                                    #       python: python3.4


python_bin: /usr/bin/python
python_pkg_bin: /usr/local/bin
python_yum_disablerepo: no
python_yum_enablerepo: no
